
'use strict'


// 所有的 tag 标签，全部使用单数形式
// 对于扩展的标签名，使用大驼峰格式（区别于常规标签）
// 项目中引用全用同名大驼峰，必要情况可以加 Plus 前缀

/*
  组件分类：
  - HTML 标签扩展，如: Switch Dialog Toast Progress Preloader SearchBar ActionSheet
  - 经典布局 如：card list-block login-screen msg-page
    (极尽升华，仅使用一个或两个标签组合实现，可用于作为 HTML 标签的扩展)
*/

var list_tags = [
  // {
  //   "icon": "",
  //   "link": "layout",
  //   "title": "基本结构",
  //   "small": "layout",
  //   "type": "base",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "rem",
  //   "title": "使用rem",
  //   "small": "1rem = 20px",
  //   "type": "base",
  //   "status": "done",
  // },
  // {
  //   "icon": "",
  //   "link": "init",
  //   "title": "初始化",
  //   "small": "init",
  //   "type": "base",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "router",
  //   "title": "路由",
  //   "small": "使用 vue-router",
  //   "type": "base",
  //   "status": "",
  // },
  // {
  //   "icon": "",
  //   "link": "content",
  //   "title": "内容区",
  //   "small": "content",
  //   "type": "base",
  //   "status": "doing",
  // },
  {
    "icon": "",
    "link": "typography",
    "title": "排版样式",
    "small": "typography",
    "type": "base",
    "status": "doing",
  },
  {
    "icon": "",
    "link": "button",
    "title": "按钮",
    "small": "button",
    "type": "form",
    "status": "doing",
  },
  // {
  //   "icon": "",
  //   "link": "icon",
  //   "title": "图标",
  //   "small": "icon",
  //   "type": "img",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "badge",
  //   "title": "徽章",
  //   "small": "badge",
  //   "type": "layout",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "group",
  //   "title": "分组",
  //   "small": "group",
  //   "type": "layout",
  //   "status": "doing",
  // },
  {
    "icon": "",
    "link": "switch",
    "title": "开关",
    "small": "switch",
    "type": "form",
    "status": "doing",
  },
  // {
  //   "icon": "",
  //   "link": "list",
  //   "title": "列表",
  //   "small": "List Block",
  //   "type": "layout",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "grid",
  //   "title": "栅格",
  //   "small": "grid",
  //   "type": "base",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "img",
  //   "title": "图片",
  //   "small": "img",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "form",
  //   "title": "表单",
  //   "small": "form",
  //   "type": "form",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "tab",
  //   "title": "Tab切换",
  //   "small": "Tab",
  //   "type": "layout",
  //   "status": "todo",
  // },
  {
    "icon": "",
    "link": "navbar",
    "title": "标题栏",
    "small": "navbar",
    "type": "bar",
    "status": "doing",
  },
  // {
  //   "icon": "",
  //   "link": "toolbar",
  //   "title": "工具栏",
  //   "small": " toolbar",
  //   "type": "bar",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "searchbar",
  //   "title": "搜索栏",
  //   "small": "Search Bar",
  //   "type": "bar",
  //   "status": "doing",
  // },
  // {
  //   "icon": "",
  //   "link": "panel",
  //   "title": "侧边栏",
  //   "small": "Side Panel",
  //   "type": "bar",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "card",
  //   "title": "卡片",
  //   "small": "Card",
  //   "type": "layout",
  //   "status": "todo",
  // },
  {
    "icon": "",
    "link": "modal",
    "title": "对话框",
    "small": "Modal",
    "type": "layout",
    "status": "todo",
  },
  // {
  //   "icon": "",
  //   "link": "notification",
  //   "title": "消息提醒",
  //   "small": "Notification",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "picker",
  //   "title": "选择器",
  //   "small": "Picker",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "datetime-picker",
  //   "title": "日期时间",
  //   "small": "Datetime Picker",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "city-picker",
  //   "title": "省市区",
  //   "small": "City Picker",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "action-sheet",
  //   "title": "操作表",
  //   "small": "ActionSheet",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "popover",
  //   "title": "弹出提醒",
  //   "small": "Popover",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "preloader",
  //   "title": "加载指示器",
  //   "small": "Preloader",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "progressbar",
  //   "title": "进度条",
  //   "small": "Progress Bar",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "pull-to-refresh",
  //   "title": "下拉刷新",
  //   "small": "Pull To Refresh",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "address",
  //   "title": "地址选择",
  //   "small": "address",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "Toast",
  //   "title": "消息提示",
  //   "small": "Toast",
  //   "type": "plus_tags",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "Progress",
  //   "title": "进度条",
  //   "small": "Progress",
  //   "type": "plus_tags",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "accordion",
  //   "title": "手风琴",
  //   "small": "Accordion",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "autocomplete",
  //   "title": "自动补全",
  //   "small": "Autocomplete",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "calendar",
  //   "title": "日历",
  //   "small": "Calendar / Datepicker",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "toast",
  //   "title": "消息提示框",
  //   "small": "Toast",
  //   "type": "layout",
  //   "status": "todo",
  // },
  //
  // {
  //   "icon": "",
  //   "link": "contact",
  //   "title": "联系人列表",
  //   "small": "Contacts List",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "infinite-scroll",
  //   "title": "无限滚动",
  //   "small": "Infinite Scroll",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "lazy-load",
  //   "title": "延迟加载",
  //   "small": "Lazy Load Image",
  //   "type": "layout",
  //   "status": "todo",
  // },
  //
  // {
  //   "icon": "",
  //   "link": "login-screen",
  //   "title": "登录界面",
  //   "small": "Login Screen",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "media-list",
  //   "title": "媒体列表",
  //   "small": "Media List",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "message",
  //   "title": "消息",
  //   "small": "Message",
  //   "type": "layout",
  //   "status": "todo",
  // },
  //
  //
  // {
  //   "icon": "",
  //   "link": "sortable-list",
  //   "title": "排序列表",
  //   "small": "Sortable List",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "swipe-delete",
  //   "title": "滑动删除",
  //   "small": "Swipe To Delete",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "swiper",
  //   "title": "幻灯片",
  //   "small": "Swiper Slider",
  //   "type": "layout",
  //   "status": "todo",
  // },
  // {
  //   "icon": "",
  //   "link": "photo-browser",
  //   "title": "图片浏览器",
  //   "small": "Photo Browser",
  //   "type": "layout",
  //   "status": "todo",
  // },
  //
  // {
  //   "icon": "",
  //   "link": "virtual-list",
  //   "title": "虚拟列表",
  //   "small": "Virtual List",
  //   "type": "layout",
  //   "status": "todo",
  // }
];

module.exports = list_tags
